scrape_configs:

- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - prometheus:9090
    - cadvisor:8080

- job_name: docker
  scrape_interval: 5s
  static_configs:
  - targets:
    - 10.52.28.66:9323
    
